"""Add ActivityState table2

Revision ID: d04950c5a624
Revises: d3631b8bb652
Create Date: 2024-07-27 09:36:50.422693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d04950c5a624"
down_revision = "d3631b8bb652"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_state", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("s3_file_path", sa.String(length=256), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_state", schema=None) as batch_op:
        batch_op.drop_column("s3_file_path")

    # ### end Alembic commands ###
